mcp: move query.rs tests module to end of file
clippy under -D warnings flags `clippy::items-after-test-module` because
the #[cfg(test)] mod tests block introduced for SEMCODE_GIT_REPO sits
mid-file with non-test items below it:

    error: items after a test module
       --> src/bin/query.rs:86:1

Move the tests module to the bottom of the file. No functional change
intended.

Signed-off-by: Chris Mason <clm@meta.com>